src/beans/Contribution.java
package beans;

import java.io.Serializable;
import java.sql.Timestamp;


public class Contribution implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String subject;
	private String text;
	private String category;
	private Timestamp created_at;
	private String name;
	private int user_id;

	public void setId(int id) {
		this.id = id;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public void setText(String text) {
		this.text = text;
	}

	public void setCategory (String category) {
		this.category = category;
	}

	public void setCreatedAt (Timestamp created_at) {
		this.created_at = created_at;
	}

	public void setUserId (int user_id) {
		this.user_id = user_id;
	}

	public int getId() {
		return this.id;
	}

	public String getSubject() {
		return this.subject;
	}

	public String getText() {
		return this.text;
	}

	public String getCategory() {
		return this.category;
	}

	public Timestamp getCreatedAt() {
		return this.created_at;
	}

	public int getUserId() {
		return user_id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}

src/controller/ContributionServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Contribution;
import service.ContributionService;

/**
 * Servlet implementation class ContributionServlet
 */
@WebServlet(urlPatterns = {"/contribution"})
public class ContributionServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();

		request.setAttribute("id", session.getAttribute("loginUser"));

		request.getRequestDispatcher("/contribution.jsp").forward(request, response);

	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();

		Contribution contribution = new Contribution();

		List<String> messages = new ArrayList<String>();


		// 改行コードを取り除いた文字列を配列に格納。
		String[] noNewLineText = request.getParameter("text").split("\r\n");

		// textの文字数を確認したい為、0で初期化。
		int textCount = 0;

		// textCountに文字数を足していく。
		for (int i = 0; i < noNewLineText.length; i++) {
			textCount += noNewLineText[i].length();
		}


		if (StringUtils.isBlank(request.getParameter("subject")) == true) {

			messages.add("件名が空です");
		} else if (request.getParameter("subject").length() >= 31) {

			messages.add("件名の文字数が30文字以内ではありません");
		} else {
			contribution.setSubject(request.getParameter("subject"));
		}

		if (StringUtils.isBlank(request.getParameter("category")) == true) {

			messages.add("カテゴリーが空です");
		} else if (request.getParameter("category").length() >= 11) {

			messages.add("カテゴリーの文字数が10文字以内ではありません");
		} else {
			contribution.setCategory(request.getParameter("category"));
		}


		if (StringUtils.isBlank(request.getParameter("text")) == true) {
			messages.add("本文が空です");
		} else if (textCount >= 1001) {

			messages.add("本文の文字数が1000文字以内ではありません");
		} else {
			contribution.setText(request.getParameter("text"));
		}

		// ログインしているユーザーIDをセッションから受け取りintにキャストしてidに格納。
		int id = (int) session.getAttribute("loginUser");

		contribution.setUserId(id);

		if (messages.size() == 0) {

			new ContributionService().Store(contribution);
			response.sendRedirect("./");

		} else {

			request.setAttribute("subject", request.getParameter("subject"));
			request.setAttribute("category", request.getParameter("category"));
			request.setAttribute("text", request.getParameter("text"));
			request.setAttribute("messages", messages);
			request.getRequestDispatcher("/contribution.jsp").forward(request, response);
		}


	}

}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Comment;
import beans.Contribution;
import beans.User;
import service.CommentService;
import service.ContributionService;
import service.LoginService;

@WebServlet(urlPatterns = {"/login"} )
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;





	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		request.getRequestDispatcher("/login.jsp").forward(request, response);
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		User user = loginService.login(login_id, password);




		HttpSession session = request.getSession();

		if(user != null && user.getIsDeleted() == 0) {

			session.setAttribute("loginUser", user.getId());
			session.setAttribute("loginUserName", user.getName());
			session.setAttribute("position_id", user.getPositionId());
			session.setAttribute("is_deleted", user.getIsDeleted());

			Date now = new Date();
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");

			String nowDate = sdf.format(now);


			String created_at1 = request.getParameter("created_at1");
			String created_at2 = request.getParameter("created_at2");
			String category = request.getParameter("category");


			if (StringUtils.isBlank(request.getParameter("created_at1")) == true) {
				created_at1 = "2018-01-01-00-00-00";
			} else {
				created_at1 = request.getParameter("created_at1");
			}


			if (StringUtils.isBlank(request.getParameter("created_at2")) == true) {
				created_at2 = nowDate;
			} else {
				created_at2 = request.getParameter("created_at2");
			}




			List<Contribution> contributions = new ContributionService().getContribution(created_at1, created_at2, category);

			request.setAttribute("contributions", contributions);

			List<Comment> comments = new CommentService().getComment();

			request.setAttribute("comments", comments);

			response.sendRedirect("./");



		} else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました");
			request.setAttribute("login_id", login_id);
			session.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("/login.jsp").forward(request, response);
		}


	}

}

src/controller/SettingServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import beans.UserInfomation;
import service.SetNameService;
import service.SettingService;
import service.UserInfomationService;
import service.UserService;


@WebServlet(urlPatterns = {"/setting"})
public class SettingServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();


		List<String> messages = new ArrayList<String>();

		if((StringUtils.isBlank(request.getParameter("id")) == true)) {

			List<UserInfomation> infomations = new UserInfomationService().getInfomations();

			request.setAttribute("infomations", infomations);

			messages.add("不正なパラメーターが入力されました");
			session.setAttribute("errorMessages", messages);


			response.sendRedirect("management");
			return;
		}

		boolean user = UserService.existence(request.getParameter("id"));

		if (request.getParameter("id").matches("^[0-9]*$") &&
				user == true){

			int id = (int) session.getAttribute("loginUser");

			request.setAttribute("id", request.getParameter("id"));
			request.setAttribute("loginUser", id);


			List<UserInfomation> name = new SetNameService().getUserName(Integer.parseInt(request.getParameter("id")));
			List<UserInfomation> branches = new SetNameService().getBranchNames();
			List<UserInfomation> positions = new SetNameService().getPositionNames();


			request.setAttribute("name", name);
			request.setAttribute("branches", branches);
			request.setAttribute("positions", positions);



			request.getRequestDispatcher("setting.jsp").forward(request, response);

		} else if (StringUtils.isBlank(request.getParameter("id")) == true) {

			List<UserInfomation> infomations = new UserInfomationService().getInfomations();

			request.setAttribute("infomations", infomations);

			messages.add("不正なパラメーターが入力されました");
			session.setAttribute("errorMessages", messages);


			response.sendRedirect("management");

		} else {

			List<UserInfomation> infomations = new UserInfomationService().getInfomations();

			request.setAttribute("infomations", infomations);

			messages.add("不正なパラメーターが入力されました");
			session.setAttribute("errorMessages", messages);


			response.sendRedirect("management");
		}






	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {


		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();

		int id = Integer.parseInt(request.getParameter("id"));
		int checkId = (int) session.getAttribute("loginUser");

		if (id == checkId) {

			String login_id = request.getParameter("login_id");
			String username = request.getParameter("name");
			String password = request.getParameter("password");
			String passwordCheck = request.getParameter("password_check");



			User user = new User();
			User userCheck = new User();

			userCheck = UserService.check(login_id);

			if (StringUtils.isBlank(login_id) == true) {

				String notChange = null;
				user.setLoginId(notChange);
			}

			if (StringUtils.isBlank(login_id) != true) {

				if ((login_id.length() >= 6) != true || (login_id.length() <= 20) != true) {

					messages.add("ログインIDは6文字以上20文字以下で入力してください");
				} else if (login_id.matches("^[0-9a-zA-Z]+$") != true) {

					messages.add("ログインIDは半角英数字のみ登録出来ます");

				} else if (userCheck != null) {

					String notChange = null;
					user.setLoginId(notChange);
				} else {

					user.setLoginId(login_id);
				}
			}


			if (StringUtils.isBlank(password) == true && (StringUtils.isBlank(passwordCheck)) == true) {

				String notChange = null;
				user.setPassword(notChange);
			}

			if ((StringUtils.isBlank(password)) != true) {

				if (password.equals(passwordCheck) != true) {

					messages.add("パスワードが合っていません");
				} else if ((password.length() >= 6) != true || (password.length() <= 20) != true) {

					messages.add("パスワードは6文字以上20文字以下で入力してください");
				} else if (password.matches("^[a-zA-Z0-9-/:-@\\[-\\`\\{-\\~]+$") != true) {

					messages.add("パスワードは半角英数字と記号のみ登録出来ます");
				} else {

					user.setPassword(password);
				}
			}

			// idを取得。
			user.setId(id);

			// 名前が空の場合エラーメッセージを表示。
			if (StringUtils.isEmpty(username) != true) {
				user.setName(username);
			} else {
				messages.add("名前を入力してください");
			}

			// passwordの内容を確認して取得。




			// エラーメッセージがあれば、エラーメッセージを表示し編集画面に戻る。
			if (messages.size() == 0 && user.getPassword() != null) {

				new SettingService().selfEdit(user);
				response.sendRedirect("management");
			} else if (messages.size() == 0 && user.getPassword() == null) {

				new SettingService().passwordNotSelfEdit(user);
				response.sendRedirect("management");
			} else {


				List<UserInfomation> name = new SetNameService().getUserName(id);


				request.setAttribute("name", name);
				// request.setAttribute("failName", username);
				request.setAttribute("password", password);
				request.setAttribute("passwordCheck", passwordCheck);


				request.setAttribute("id", id);
				request.setAttribute("messages", messages);
				request.getRequestDispatcher("setting.jsp").forward(request, response);
			}

		}

		if (id != checkId) {

			String login_id = request.getParameter("login_id");
			String username = request.getParameter("name");
			String password = request.getParameter("password");
			String passwordCheck = request.getParameter("password_check");
			int branch_id = Integer.parseInt(request.getParameter("branch_id"));
			int position_id = Integer.parseInt(request.getParameter("position_id"));


			User user = new User();

			User userCheck = new User();

			userCheck = UserService.check(login_id);

			if (StringUtils.isBlank(login_id) == true) {

				String notChange = null;
				user.setLoginId(notChange);
			}

			if (StringUtils.isBlank(login_id) != true) {

				if ((login_id.length() >= 6) != true || (login_id.length() <= 20) != true) {

					messages.add("ログインIDは6文字以上20文字以下で入力してください");
				} else if (login_id.matches("^[0-9a-zA-Z]+$") != true) {

					messages.add("ログインIDは半角英数字のみ登録出来ます");

				} else if (userCheck != null) {

					String notChange = null;
					user.setLoginId(notChange);
				} else {

					user.setLoginId(login_id);
				}
			}


			if (StringUtils.isBlank(password) == true && (StringUtils.isBlank(passwordCheck)) == true) {

				String notChange = null;
				user.setPassword(notChange);
			}

			if ((StringUtils.isBlank(password)) != true) {

				if (password.equals(passwordCheck) != true) {

					messages.add("パスワードが合っていません");
				} else if ((password.length() >= 6) != true || (password.length() <= 20) != true) {

					messages.add("パスワードは6文字以上20文字以下で入力してください");
				} else if (password.matches("^[a-zA-Z0-9-/:-@\\[-\\`\\{-\\~]+$") != true) {

					messages.add("パスワードは半角英数字と記号のみ登録出来ます");
				} else {

					user.setPassword(password);
				}
			}

			// idを取得。
			user.setId(id);

			// 名前が空の場合エラーメッセージを表示。
			if (StringUtils.isEmpty(username) != true) {
				user.setName(username);
			} else {
				messages.add("名前を入力してください");
			}

			// passwordの内容を確認して取得。

			/*if ((StringUtils.isBlank(password) == true) && (StringUtils.isBlank(passwordCheck) == true)) {

				String notChange = null;
				user.setPassword(notChange);
			} else */

			// branch_idとposition_idの組み合わせをチェック
			if ((branch_id == 1 && (position_id != 1 && position_id != 2)) ||
					(branch_id != 1 && (position_id == 1 || position_id == 2))){

				messages.add("支店名と役職名の組み合わせが不正です");
			} else {
				user.setBranchId(branch_id);
				user.setPositionId(position_id);
			}


			// エラーメッセージがあれば、エラーメッセージを表示し編集画面に戻る。
			if (messages.size() == 0 && user.getPassword() != null) {

				new SettingService().edit(user);
				response.sendRedirect("management");
			} else if (messages.size() == 0 && user.getPassword() == null) {

				new SettingService().passwordNotEdit(user);
				response.sendRedirect("management");
			} else {


				List<UserInfomation> name = new SetNameService().getUserName(id);
				List<UserInfomation> branches = new SetNameService().getBranchNames();
				List<UserInfomation> positions = new SetNameService().getPositionNames();


				request.setAttribute("name", name);
				// request.setAttribute("failName", username);
				request.setAttribute("password", password);
				request.setAttribute("passwordCheck", passwordCheck);
				request.setAttribute("branches", branches);
				request.setAttribute("positions", positions);


				request.setAttribute("id", id);
				request.setAttribute("messages", messages);
				request.getRequestDispatcher("setting.jsp").forward(request, response);
			}


			/*if (StringUtils.isBlank(login_id) == true) {

				String notChange = null;
				user.setLoginId(notChange);
			}

			if (StringUtils.isBlank(login_id) != true) {

				if ((login_id.length() >= 6) != true || (login_id.length() <= 20) != true) {

					messages.add("ログインIDは6文字以上20文字以下で入力してください");
				} else if (login_id.matches("^[0-9a-zA-Z]+$") != true) {

					messages.add("ログインIDは半角英数字のみ登録出来ます");

				} else if (userCheck != null) {

					String notChange = null;
					user.setLoginId(notChange);
				} else {

					user.setLoginId(login_id);
				}
			}


			if (StringUtils.isBlank(password) == true && (StringUtils.isBlank(passwordCheck)) == true) {

				String notChange = null;
				user.setPassword(notChange);
			}

			if ((StringUtils.isBlank(password)) != true) {

				if (password.equals(passwordCheck) != true) {

					messages.add("パスワードが合っていません");

WebContent/contribution.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>新規投稿画面</title>

<script type="text/javascript">


function check(){

	if(window.confirm('投稿してよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}

</script>

</head>
<body>

	<c:if test="${ not empty messages }">
		<div class="messages">
			<ul>
				<c:forEach items="${messages}" var="message">
					<li><c:out value="${message}" />
				</c:forEach>
			</ul>
		</div>
		<c:remove var="messages" scope="session"/>
	</c:if>

	<div>
		<form action="contribution" method="post" onSubmit="return check()">
			<label for="subject">件名(30文字まで)</label><br>
			<input type="text" name="subject" id="subject" value="${subject}"maxlength="30"><br/>

			<label for="category">カテゴリー(10文字まで)</label><br>
			<input type="text" name="category" id="category" value="${category}"maxlength="10"><br/>

			<label for="text">本文(1000文字まで)</label><br>
			<textarea name="text" cols="100" rows="10"  id="text" >${text}</textarea>

			<input type="hidden"  name="id" value="${id}"><br/>

			<input type="submit" value="投稿">
		</form>

	</div><br/>
	<a href="./">戻る</a>
</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ログイン画面</title>
</head>

<body>

	<c:if test="${ not empty errorMessages }">
		<div class="errorMessages">
			<ul>
				<c:forEach items="${errorMessages}" var="message">
					<li><c:out value="${message}" />
				</c:forEach>
			</ul>
		</div>
		<c:remove var="errorMessages" scope="session"/>
	</c:if>

	<form action="login" method="post"><br/>

	<label for="login_id">ログインID</label>
	<input name="login_id" id="login_id" value="${login_id}"/> <br/>

	<label for="password">パスワード</label>
	<input type="password" name="password" id="password" /> <br/>

	<input type="submit" value="ログイン" /> <br/>
	</form>





</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー管理画面</title>

<script type="text/javascript">


function revivalCheck(){

	if(window.confirm('ユーザーを復活してもよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}

function stopCheck(){

	if(window.confirm('ユーザーを停止してもよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}

</script>
</head>
<body>


	<c:if test="${ not empty errorMessages }">
		<div class="errorMessages">
			<ul>
				<c:forEach items="${errorMessages}" var="message">
					<li><c:out value="${message}" />
				</c:forEach>
			</ul>
		</div>
		<c:remove var="errorMessages" scope="session"/>
	</c:if>



	<a href="signup">新規登録画面</a><br/>
	<table border="1">
		<tr>
			<th>ID</th>
			<th>ログインID</th>
			<th>ユーザー名</th>
			<th>支店名</th>
			<th>役職名</th>
			<th>アカウント状況</th>
			<th>編集</th>
		</tr>

	<c:forEach items="${infomations}" var="infomations">
		<tr>
			<td>${infomations.id}</td>
			<td>${infomations.login_id}</td>
			<td>${infomations.name}</td>
			<td>${infomations.branch_name}</td>
			<td>${infomations.position_name}</td>
			<td>
			<c:if test="${infomations.id != loginUser }" >
			<c:choose>
				<c:when test="${infomations.is_deleted == 0 }">
					<form action="stoprevival" method="post" onSubmit="return stopCheck()" >
						<input type="hidden" name="id" value="${infomations.id }" />
						<input type="hidden" name="is_deleted" value="${infomations.is_deleted}" />
						<input type="submit" value="停止" />
					</form>
				</c:when>
				<c:when test="${infomations.is_deleted == 1 }">
					<form action="stoprevival" method="post" onSubmit="return revivalCheck()" >
						<input type="hidden" name="id" value="${infomations.id }" />
						<input type="hidden" name="is_deleted" value="${infomations.is_deleted }" />
						<input type="submit" value="復活" />
					</form>
				</c:when>
			</c:choose>
			</c:if>
			</td>
			<td><a href="setting?id=${infomations.id}">編集</a></td>
		</tr>




	</c:forEach>
	</table>

	<a href="./">戻る</a>

</body>
</html>

WebContent/top.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>top</title>

<script type="text/javascript">


function deletecheck(){

	if(window.confirm('削除してよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}

function check(){

	if(window.confirm('コメントしてよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}



</script>

<style type="text/css">



.contribution-names{

	border-style: solid;
	background-color: yellow;
	word-wrap: break-word;


	margin: 10 auto;
}

#wrap {

	word-wrap: break-word;
}

.comment-List {

	margin-top: 10px;
	background-color: #B5FF14;
	border-style: solid;
	word-wrap: break-word;

	margin: 10 auto;
}



</style>
</head>
<body>



		<div class="header">
			<c:if test="${ empty loginUser }">
			<a href="login">ログイン</a>
			</c:if>

			<c:if test="${ not empty loginUser }">
			<div class="headline">
				<a href="./">ホーム</a>
				<a href="contribution?id=${loginUser}">新規投稿</a>
				<a href="management">ユーザー管理</a>
				<a href="logout">ログアウト</a>
			</div>

			<div class="search">
			<form action="./" method="get" >
				<input type="date" name="start" value="${start}"/>
				<input type="date" name="end"  value="${end}"/>
				<input type="text" name="category" value="${category }"/>
				<input type="submit" value="絞り込み" />
			</form>
			</div>

			<h3>${loginUserName}さん</h3>
			<input type="hidden" name="is_deleted" value="${is_deleted}" />
			<input type="hidden" name="position_id" value="${position_id}" />
			</c:if>
		</div>

		<c:if test="${ not empty messages }">
		<div class="messages">
			<ul>
			<c:forEach items="${messages}" var="message">
				<li><c:out value="${message}" />
			</c:forEach>
			</ul>
		</div>
			<c:remove var="messages" scope="session" />
		</c:if>


	<div class="null">
	</div>


	<div class="contributions">

		<c:forEach items="${contributions}" var="contributions">
		<div class="contribution">
			<div class="contribution-names">
				<span class="subject">件名:<c:out value="${contributions.subject}" /></span><br />
				<span class="category">カテゴリー:<c:out value="${contributions.category}" /></span><br />
				<span class="name">名前:<c:out value="${contributions.name}" /></span><br />
				<span>本文:</span><br/>
				<pre><c:out value="${contributions.text }" /></pre>
				<c:out value="${contributions.createdAt}" />
				<c:if test="${contributions.userId == loginUser }">
				<form action="delete" method="post" onSubmit="return deletecheck()">
					<input type="hidden" name="contributions.id" value="${contributions.id}" />
					<input type="submit" value="削除" />
				</form>
				</c:if>
			</div>


		</div>



			<div class="comment">
			<c:forEach items="${comments}" var="comments">
				<c:if test="${contributions.id == comments.contribution_id}">
					<div class="comment-List">
						<div>
							<span class="name">名前:<c:out value="${comments.name}" /></span><br />
							<span>本文:</span>
						</div>
						<pre><c:out value="${comments.text}" /></pre>
						<div class="comment-date">
							<c:out value="${comments.created_at}" />
						</div>

						<c:if test="${comments.user_id == loginUser }">
							<form action="commentdelete" method="post"  onSubmit="return deletecheck()">
								<input type="hidden" name="commentid" value="${comments.id}" />
								<input type="submit" value="コメント削除" />
							</form>
						</c:if>
					</div>
				</c:if>
			</c:forEach>
			</div>


			<div class="post-comment">
			<form action="comment" method="post" onSubmit="return check()" >
				<input type="hidden" name="loginUser" value="${loginUser}" /> <input
					type="hidden" name="contributionId" value="${contributions.id}" />
				<span>コメント記入欄(500文字まで)</span><br />
				<textarea name="text" rows="10" cols="40" >${text}</textarea>
				<br /> <input type="submit" value="コメント">
			</form>
			</div>



		</c:forEach>

	</div>





</body>
</html>